export const HEX_HEIGHT = 215;

export const HEX_WIDTH = 187;

export const SIDE_LENGTH = 107;

export const TRIANGLE_ALTITUDE = (HEX_HEIGHT - SIDE_LENGTH) / 2;

export const TRIANGLE_TO_SIDE_RATIO = TRIANGLE_ALTITUDE / SIDE_LENGTH;
